// Generated by Haxe 4.0.0-rc.2+77068e1
(function () { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var App = function() {
	var root = window.document.getElementById("root");
	var rootComponent = ReactDOM.render({ $$typeof : $$tre, type : Root, props : { }, key : null, ref : null},root);
};
App.main = function() {
	new App();
};
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var JsxStaticInit_$_$ = function() { };
var React_Component = require("react").Component;
var Root = function() {
	React_Component.call(this);
	this.state = { route : ""};
	var noice = import(/* webpackChunkName: "Test" */ "!haxe-loader?null/Test!").then(function(exports) {
		Test = $s.Test;
		var _ = Test;
		return exports;
	});
	console.log("src/Root.hx:16:",noice);
};
Root.__super__ = React_Component;
Root.prototype = $extend(React_Component.prototype,{
	componentDidMount: function() {
		var _gthis = this;
		var _g = this.state.route;
		import(/* webpackChunkName: "com_Foo" */ "!haxe-loader?null/com_Foo!").then(function(exports) {
			com_Foo = $s.com_Foo;
			var _ = com_Foo;
			return exports;
		}).then(function(_1) {
			_gthis.setState({ component : com_Foo});
		});
	}
	,render: function() {
		return { $$typeof : $$tre, type : "div", props : { children : [{ $$typeof : $$tre, type : "h1", props : { children : "Hello Haxe + Webpack + React"}, key : null, ref : null},this.renderContent()]}, key : null, ref : null};
	}
	,renderContent: function() {
		if(this.state.component == null) {
			return { $$typeof : $$tre, type : "span", props : { children : "Loading..."}, key : null, ref : null};
		} else {
			return { $$typeof : $$tre, type : this.state.component, props : { }, key : null, ref : null};
		}
	}
});
var Test = require("Test");
var Webpack = function() { };
var com_Foo = function(props,context) {
	React_Component.call(this,props,context);
};
com_Foo.__super__ = React_Component;
com_Foo.prototype = $extend(React_Component.prototype,{
	render: function() {
		return { $$typeof : $$tre, type : "div", props : { className : "foo", children : [{ $$typeof : $$tre, type : "img", props : { src : com_Foo.IMG}, key : null, ref : null}," ",com_Foo.CONFIG.hello,"!",{ $$typeof : $$tre, type : "hr", props : { }, key : null, ref : null},"Let's do some HRM guys",{ $$typeof : $$tre, type : "br", props : { }, key : null, ref : null}]}, key : null, ref : null};
	}
});
var react_Partial = function() { };
var react_PartialMacro = function() { };
var ReactDOM = require("react-dom");
var react_ReactMacro = function() { };
var react__$ReactRef_ReactRef_$Impl_$ = {};
react__$ReactRef_ReactRef_$Impl_$.get_current = function(this1) {
	return this1.current;
};
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
App.STYLES = require("./src/App.sass");
Root.displayName = "Root";
com_Foo.STYLES = require("./src/com/Foo.css");
com_Foo.IMG = require("./src/com/logo.svg");
com_Foo.CONFIG = require("./src/config.json");
com_Foo.displayName = "Foo";
App.main();
})();
