// Generated by Haxe 4.0.0-rc.2+77068e1
(function () { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var App = function() {
	var root = window.document.getElementById("root");
	var rootComponent = ReactDOM.render({ $$typeof : $$tre, type : Root, props : { }, key : null, ref : null},root);
};
App.main = function() {
	new App();
};
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var JsxStaticInit_$_$ = function() { };
var React_Component = require("react").Component;
var Root = function() {
	React_Component.call(this);
	this.state = { route : ""};
};
Root.__super__ = React_Component;
Root.prototype = $extend(React_Component.prototype,{
	componentDidMount: function() {
		var _gthis = this;
		var _g = this.state.route;
		import(/* webpackChunkName: "pages_homeHX_Page" */ "!haxe-loader?null/pages_homeHX_Page!").then(function(exports) {
			pages_homeHX_Page = $s.pages_homeHX_Page;
			var _ = pages_homeHX_Page;
			return exports;
		}).then(function(_1) {
			_gthis.setState({ component : pages_homeHX_Page});
		});
	}
	,render: function() {
		return { $$typeof : $$tre, type : "div", props : { children : [{ $$typeof : $$tre, type : "h1", props : { children : "Hello Haxe + Webpack + React"}, key : null, ref : null},this.renderContent()]}, key : null, ref : null};
	}
	,renderContent: function() {
		if(this.state.component == null) {
			return { $$typeof : $$tre, type : "span", props : { children : "Loading..."}, key : null, ref : null};
		} else {
			return { $$typeof : $$tre, type : this.state.component, props : { }, key : null, ref : null};
		}
	}
});
var Webpack = function() { };
var pages_homeHX_Button = require("@material-ui/core").Button;
var pages_homeHX_Page = function(props,context) {
	React_Component.call(this,props,context);
};
pages_homeHX_Page.__super__ = React_Component;
pages_homeHX_Page.prototype = $extend(React_Component.prototype,{
	render: function() {
		return React.createElement(pages_homeHX_Button,{ variant : "", color : "primary"},"Hello World!");
	}
});
var react_Partial = function() { };
var react_PartialMacro = function() { };
var React = require("react");
var ReactDOM = require("react-dom");
var react_ReactMacro = function() { };
var react__$ReactRef_ReactRef_$Impl_$ = {};
react__$ReactRef_ReactRef_$Impl_$.get_current = function(this1) {
	return this1.current;
};
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
App.STYLES = require("./src/App.sass");
App.ROBOTO = require("typeface-roboto");
Root.displayName = "Root";
pages_homeHX_Page.STYLES = require("./src/pages/homeHX/Foo.css");
pages_homeHX_Page.displayName = "Page";
App.main();
})();
